"""Used to obfuscate variables from the namespace"""

def _determine_boot()-> dict:
    """
    Reads the boot.loader file for boot order and type

    ---

    If file is empty, or non-existent and plug-ins exist within directory,
    boot.loader will be created and/or populated with an autogenerated
    boot order
    """

class Plugins:
    """Controls the loading of all the plug-ins listed by the boot.loader"""
    boot_order:dict=_determine_boot()
